csa_guzzle:
    clients:
        default:
            config:
                cert: '/etc/pki/tls/certs/client.crt'
                ssl_key: '/etc/pki/tls/private/client.key'
                verify: false
                timeout: 60
                connect_timeout: 5
