status:
    path: /status
    defaults: { _controller: App\Controller\StatusController }

root:
    path: /
    defaults: { _controller: FrameworkBundle:Redirect:redirect, route: home, permanent: true }

home:
    path: /blogs
    defaults: { _controller: App\Controller\HomeController }

blog:
    path: /blogs/{blogId}
    defaults: { _controller: App\Controller\BlogShowController }
    requirements: { blogId: '[a-z0-9]+' }

post:
    path: /blogs/{blogId}/entries/{guid}
    defaults: { _controller: FrameworkBundle:Redirect:redirect, route: '' }
    requirements: { blogId: '[a-z0-9]+' }
