status:
    path: /status
    defaults: { _controller: App\Controller\StatusController }

root:
    path: /
    defaults: { _controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction, route: home, permanent: true }

home:
    path: /blogs
    defaults: { _controller: App\Controller\HomeController }

author_index:
    path: /blogs/{blogId}/authors
    defaults: { _controller: App\Controller\AuthorIndexController }
    requirements: { blogId: '[a-z0-9]+' }

author_index_atoz:
    path: /blogs/{blogId}/authors/a-z
    defaults: { _controller: App\Controller\AuthorIndexAtoZController }
    requirements: { blogId: '[a-z0-9]+' }

author_index_atoz_letter:
    path: /blogs/{blogId}/authors/a-z/{letter}
    defaults: { _controller: App\Controller\AuthorShowAtoZController }
    requirements: { blogId: '[a-z0-9]+', letter: '[a-z]' }

author_show:
    path: /blogs/{blogId}/authors/{guid}
    defaults: { _controller: App\Controller\AuthorShowController }
    requirements: { blogId: '[a-z0-9]+', guid: '^[a-f\d]{8}(-[a-f\d]{4}){4}[a-f\d]{8}$' }

blog:
    path: /blogs/{blogId}
    defaults: { _controller: App\Controller\BlogShowController }
    requirements: { blogId: '[a-z0-9]+' }

comments_partial:
    path: /blogs/{blogId}/entries/{guid}/comments/standalone
    defaults:
        _controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
        route: post
        _fragment: 'comments'
        permanent: true
    requirements: { blogId: '[a-z0-9]+', guid: '^[a-f\d]{8}(-[a-f\d]{4}){4}[a-f\d]{8}$' }

comments_index:
    path: /blogs/{blogId}/entries/{guid}/comments
    defaults:
        _controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
        route: post
        _fragment: 'comments'
        permanent: true
    requirements: { blogId: '[a-z0-9]+', guid: '^[a-f\d]{8}(-[a-f\d]{4}){4}[a-f\d]{8}$' }

post:
    path: /blogs/{blogId}/entries/{guid}
    defaults: { _controller: App\Controller\PostShowController }
    requirements: { blogId: '[a-z0-9]+', guid: '^[a-f\d]{8}(-[a-f\d]{4}){4}[a-f\d]{8}$' }

posts_date_redirect:
    path: /blogs/{blogId}/entries
    defaults: { _controller: App\Controller\PostByDateRedirectController }
    requirements: { blogId: '[a-z0-9]+' }

posts_year:
    path: /blogs/{blogId}/entries/{year}
    requirements: { blogId: '[a-z0-9]+', year: '\d{4}' }
    defaults: { _controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction, route: posts_year_month, permanent: true, month: '01' }

posts_year_month:
    path: /blogs/{blogId}/entries/{year}/{month}
    defaults: { _controller: App\Controller\PostByDateController }
    requirements: { blogId: '[a-z0-9]+', year: '\d{4}', month: '\d{2}' }

tag_index:
    path: /blogs/{blogId}/tags
    defaults: { _controller: App\Controller\TagIndexController }
    requirements: { blogId: '[a-z0-9]+' }

tag_show:
    path: /blogs/{blogId}/tags/{tagId}
    defaults: { _controller: App\Controller\TagShowController }
    requirements: { blogId: '[a-z0-9]+', tagId: '[A-Za-z0-9-]+'}

feed_atom:
    path: /blogs/{blogId}/atom
    defaults: { _controller: App\Controller\BlogAtomFeedController }
    requirements: { blogId: '[a-z0-9]+' }

feed_rss:
    path: /blogs/{blogId}/rss
    defaults: { _controller: App\Controller\BlogRssFeedController }
    requirements: { blogId: '[a-z0-9]+' }

feed_atom_tags:
    path: /blogs/{blogId}/tags/{tagId}/atom
    defaults: { _controller: App\Controller\TagAtomFeedController }
    requirements: { blogId: '[a-z0-9]+', tagId: '[A-Za-z0-9-]+'}

feed_rss_tags:
    path: /blogs/{blogId}/tags/{tagId}/rss
    defaults: { _controller: App\Controller\TagRssFeedController }
    requirements: { blogId: '[a-z0-9]+', tagId: '[A-Za-z0-9-]+'}
