status:
    path: /status
    defaults: { _controller: App\Controller\StatusController }

root:
    path: /
    defaults: { _controller: FrameworkBundle:Redirect:redirect, route: home, permanent: true }

home:
    path: /blogs
    defaults: { _controller: App\Controller\HomeController }
