status:
    path: /status
    defaults: { _controller: App\Controller\StatusController }

root:
    path: /
    defaults: { _controller: FrameworkBundle:Redirect:redirect, route: home, permanent: true }

home:
    path: /blogs
    defaults: { _controller: App\Controller\HomeController }

blog:
    path: /blogs/{blogId}
    defaults: { _controller: App\Controller\BlogShowController }
    requirements: { blogId: '[a-z0-9]+' }

post:
    path: /blogs/{blogId}/entries/{guid}
    defaults: { _controller: App\Controller\PostShowController }
    requirements: { blogId: '[a-z0-9]+', guid: '^[a-f\d]{8}(-[a-f\d]{4}){4}[a-f\d]{8}$' }

tag_list:
    path: /blogs/{blogId}/tags
    defaults: { _controller: App\Controller\TagIndexController }
    requirements: { blogId: '[a-z0-9]+' }

tag:
    path: /blogs/{blogId}/tags/{tagId}
    defaults: { _controller: App\Controller\TagShowController }
    requirements: { blogId: '[a-z0-9]+', tagId: '[A-Za-z0-9-]+'}

feed_atom:
    path: /blogs/{blogId}/atom
    requirements: { blogId: '[a-z0-9]+', tagId: '[A-Za-z0-9-]+'}

feed_rss:
    path: /blogs/{blogId}/rss
    requirements: { blogId: '[a-z0-9]+', tagId: '[A-Za-z0-9-]+'}

feed_atom_tags:
    path: /blogs/{blogId}/tags/{tagId}/atom
    requirements: { blogId: '[a-z0-9]+', tagId: '[A-Za-z0-9-]+'}

feed_rss_tags:
    path: /blogs/{blogId}/tags/{tagId}/rss
    requirements: { blogId: '[a-z0-9]+', tagId: '[A-Za-z0-9-]+'}
