parameters:
    app.branding_client.class: BBC\BrandingClient\BrandingStubClient
    app.orbit_client.class: BBC\BrandingClient\OrbitStubClient
    app.metric_backend.class: App\Metrics\Backend\NullMetricBackend
    app.metric_cache.class: App\Metrics\Cache\MetricCacheNull

services:
    App\BlogsService\Service\AuthorService:
        public: true

    App\BlogsService\Service\BlogService:
        public: true

    App\BlogsService\Service\PostService:
        public: true

    App\BlogsService\Service\TagService:
        public: true

    App\BlogsService\Service\LegacyBlogService:
        class: App\BlogsService\StubService\LegacyBlogStubService

    cache.null_provider:
        class: Symfony\Component\Cache\Adapter\NullAdapter
