# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    app.default_locale: 'en_GB'
    app.orbit_client.class: BBC\BrandingClient\OrbitClient
    app.branding_client.class: BBC\BrandingClient\BrandingClient
    app.feed_env.orbit: 'live'
    app.feed_env.branding: 'live'
    cosmos_component_release: '%env(APP_RELEASE_NUMBER)%'

services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        # you can exclude directories or files
        # but if a service is unused, it's removed anyway
        exclude: '../src/{Entity,Migrations,Repository,Tests}'

    # controllers are imported separately to make sure they
    # have the tag that allows actions to type-hint services
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    BBC\BrandingClient\BrandingClient:
        class: "%app.branding_client.class%"
        arguments:
            - '@csa_guzzle.client.default'
            - '@cache.null_provider'
            - env: '%app.feed_env.branding%'
              cacheKeyPrefix: 'frontend.%cosmos_component_release%.branding'

    BBC\BrandingClient\OrbitClient:
        class: '%app.orbit_client.class%'
        arguments:
            - '@csa_guzzle.client.default'
            - '@cache.null_provider'
            - env: '%app.feed_env.orbit%'
              cacheKeyPrefix: 'frontend.%cosmos_component_release%.orbit'
              mustache: { cache: '%kernel.cache_dir%/mustache' }

    cache.null_provider:
        class: Symfony\Component\Cache\Adapter\NullAdapter

    ### Translations

    App\Translate\TranslateProvider:
        public: true

    RMP\Translate\TranslateFactory:
        arguments:
            - fallback_locale: 'en_GB'
              cachepath: '%kernel.cache_dir%/config/translations'
              domains: ['blogs']
              default_domain: 'blogs'
              debug: '%kernel.debug%'
              basepath: '%kernel.project_dir%/config/translations'
