parameters:
    app.branding_client.class: BBC\BrandingClient\BrandingStubClient
    app.orbit_client.class: BBC\BrandingClient\OrbitStubClient

services:
    App\BlogsService\Service\BlogService:
        public: true

    cache.null_provider:
        class: Symfony\Component\Cache\Adapter\NullAdapter
